name: Build and Test Server on PR
on:
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_SERVER: tjanl/server-${{ github.event.repository.name }}

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1   

      - name: Install dependencies
        working-directory: server
        run: poetry install

      - name: Run tests
        working-directory: server
        run: poetry run pytest

  build-server-image:
    needs:
      - test-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHRC_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SERVER }}

      - name: Build Docker image with PR number tag
        uses: docker/build-push-action@v5
        with:
          context: server
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SERVER }}:pr-${{ github.event.number }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            API_HOST=http://${{ secrets.TS_NODE_IP }}:8000
            COMMIT=${{ github.sha }}
